Repository newb1er/mellowmax_softmax, pull requests merged in 2022-05, with the labels that each got.

#8 Feature/register env
  mellowmax_softmax/__init__.py
  mellowmax_softmax/envs/__init__.py
  mellowmax_softmax/envs/simple_mdp.py
  mellowmax_softmax/scripts/start_experiment.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#16 Feature/test
  .github/workflows/test.yml
  poetry.lock
  pyproject.toml
  test/test_envs.py
Labels: enhancement

#22 hotfix: avoid divided by 0
  mellowmax_softmax/scripts/random_mdp_exp.py
Labels: bug
